from datetime import timedelta
from talconfig import REDIS_SERVER_HOSTNAME, REDIS_SERVER_PORT

BROKER_BACKEND = "redis"
BROKER_URL = "redis://" + REDIS_SERVER_HOSTNAME + ":" + str(REDIS_SERVER_PORT) + "/0"
CELERY_RESULT_BACKEND = "redis://" + REDIS_SERVER_HOSTNAME + ":" + str(REDIS_SERVER_PORT) + "/0"

CELERY_TRACK_STARTED = True
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CELERYCAM_EXPIRE_SUCCESS = timedelta(weeks=520)
CELERYCAM_EXPIRE_ERROR = timedelta(weeks=520)
CELERYCAM_EXPIRE_PENDING = timedelta(weeks=520)

BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 172800} # 2 days

#CELERY_ALWAYS_EAGER = True
#CELERY_EAGER_PROPAGATES_EXCEPTIONS = True

#CELERY_IMPORTS = ("talent.tasks", )
