BASE_DIR = "/opt/boglab"
GENOME_DIR = BASE_DIR + "/genome_data"
GENOME_FILE = GENOME_DIR + "/%s.fasta"
PROMOTEROME_DIR = BASE_DIR + "/promoterome_data"
PROMOTEROME_FILE = PROMOTEROME_DIR + "/%s.fasta"
RVD_SEQ_REGEX = r'^(?:(?:[ACDEFGHIKLMNPQRSTVWY][ACDEFGHIKLMNPQRSTVWY\*])[ _]+){11,30}(?:[ACDEFGHIKLMNPQRSTVWY][ACDEFGHIKLMNPQRSTVWY\*])$'
#DRUPAL_CALLBACK_URL = "http://talent.local/talent/jobcomplete/"
DRUPAL_CALLBACK_URL = "https://tale-nt.cac.cornell.edu/talent/jobcomplete/"
VALID_GENOME_ORGANISMS = ['drosophila_melanogaster', 'arabidopsis_thaliana', 'mus_musculus', 'oryza_sativa', 'caenorhabditis_elegans', 'danio_rerio', 'homo_sapiens', 'rattus_norvegicus', 'brachypodium_distachyon', 'solanum_lycopersicum']
VALID_PROMOTEROME_ORGANISMS = ['drosophila_melanogaster', 'arabidopsis_thaliana', 'mus_musculus', 'oryza_sativa', 'caenorhabditis_elegans', 'danio_rerio', 'homo_sapiens', 'rattus_norvegicus', 'brachypodium_distachyon']
