#!/usr/bin/python

import re
import pickle

#List of NEB enzyme sequences and regex
NEB_RE_sites = {
    "AatII": "GACGTC",
    "Acc65I": "GGTACC",
    "AccI": "GT[AC][GT]AC",
    "AciI": "CCGC|GCGG",
    "AclI": "AACGTT",
    "AcuI": "CTGAAG|CTTCAG",
    "AfeI": "AGCGCT",
    "AflII": "CTTAAG",
    "AflIII": "AC[AG][CT]GT",
    "AgeI": "ACCGGT",
    "AhdI": "GAC[ACGT][ACGT][ACGT][ACGT][ACGT]GTC",
    "AleI": "CAC[ACGT][ACGT][ACGT][ACGT]GTG",
    "AluI": "AGCT",
    "AlwI": "GGATC|GATCC",
    "AlwNI": "CAG[ACGT][ACGT][ACGT]CTG",
    "ApaI": "GGGCCC",
    "ApaLI": "GTGCAC",
    "ApeKI": "GC[AT]GC",
    "ApoI": "[AG]AATT[CT]",
    "AscI": "GGCGCGCC",
    "AseI": "ATTAAT",
    "AsiSI": "GCGATCGC",
    "AvaI": "C[CT]CG[AG]G",
    "AvaII": "GG[AT]CC",
    "AvrII": "CCTAGG",
    "BaeGI": "G[GT]GC[AC]C",
    "BaeI": "AC[ACGT][ACGT][ACGT][ACGT]GTA[CT]C|G[AG]TAC[ACGT][ACGT][ACGT][ACGT]GT",
    "BamHI": "GGATCC",
    "BanI": "GG[CT][AG]CC",
    "BanII": "G[AG]GC[CT]C",
    "BbsI": "GAAGAC|GTCTTC",
    "BbvCI": "CCTCAGC|GCTGAGG",
    "BbvI": "GCAGC|GCTGC",
    "BccI": "CCATC|GATGG",
    "BceAI": "ACGGC|GCCGT",
    "BcgI": "CGA[ACGT][ACGT][ACGT][ACGT][ACGT][ACGT]TGC|GCA[ACGT][ACGT][ACGT][ACGT][ACGT][ACGT]TCG",
    "BciVI": "GTATCC|GGATAC",
    "BclI": "TGATCA",
    "BcoDI": "GTCTC|GAGAC",
    "BfaI": "CTAG",
    "BfuAI": "ACCTGC|GCAGGT",
    "BfuCI": "GATC",
    "BglI": "GCC[ACGT][ACGT][ACGT][ACGT][ACGT]GGC",
    "BglII": "AGATCT",
    "BlpI": "GCT[ACGT]AGC",
    "BmgBI": "CACGTC|GACGTG",
    "BmrI": "ACTGGG|CCCAGT",
    "BmtI": "GCTAGC",
    "BpmI": "CTGGAG|CTCCAG",
    "Bpu10I": "CCT[ACGT]AGC|GCT[ACGT]AGG",
    "BpuEI": "CTTGAG|CTCAAG",
    "BsaAI": "[CT]ACGT[AG]",
    "BsaBI": "GAT[ACGT][ACGT][ACGT][ACGT]ATC",
    "BsaHI": "G[AG]CG[CT]C",
    "BsaI": "GGTCTC|GAGACC",
    "BsaJI": "CC[ACGT][ACGT]GG",
    "BsaWI": "[AT]CCGG[AT]",
    "BsaXI": "AC[ACGT][ACGT][ACGT][ACGT][ACGT]CTCC|GGAG[ACGT][ACGT][ACGT][ACGT][ACGT]GT",
    "BseRI": "GAGGAG|CTCCTC",
    "BseYI": "CCCAGC|GCTGGG",
    "BsgI": "GTGCAG|CTGCAC",
    "BsiEI": "CG[AG][CT]CG",
    "BsiHKAI": "G[AT]GC[AT]C",
    "BsiWI": "CGTACG",
    "BslI": "CC[ACGT][ACGT][ACGT][ACGT][ACGT][ACGT][ACGT]GG",
    "BsmAI": "GTCTC|GAGAC",
    "BsmBI": "CGTCTC|GAGACG",
    "BsmFI": "GGGAC|GTCCC",
    "BsmI": "GAATGC|GCATTC",
    "BsoBI": "C[CT]CG[AG]G",
    "Bsp1286I": "G[AGT]GC[ACT]C",
    "BspCNI": "CTCAG|CTGAG",
    "BspDI": "ATCGAT",
    "BspEI": "TCCGGA",
    "BspHI": "TCATGA",
    "BspMI": "ACCTGC|GCAGGT",
    "BspQI": "GCTCTTC|GAAGAGC",
    "BsrBI": "CCGCTC|GAGCGG",
    "BsrDI": "GCAATG|CATTGC",
    "BsrFI": "[AG]CCGG[CT]",
    "BsrGI": "TGTACA",
    "BsrI": "ACTGG|CCAGT",
    "BssHII": "GCGCGC",
    "BssKI": "CC[ACGT]GG",
    "BssSI": "CACGAG",
    "BstAPI": "GCA[ACGT][ACGT][ACGT][ACGT][ACGT]TGC",
    "BstBI": "TTCGAA",
    "BstEII": "GGT[ACGT]ACC",
    "BstNI": "CC[AT]GG",
    "BstUI": "CGCG",
    "BstXI": "CCA[ACGT][ACGT][ACGT][ACGT][ACGT][ACGT]TGG",
    "BstYI": "[AG]GATC[CT]",
    "BstZ17I": "GTATAC",
    "Bsu36I": "CCT[ACGT]AGG",
    "BtgI": "CC[AG][CT]GG",
    "BtgZI": "GCGATG|CATCGC",
    "BtsCI": "GGATG|CATCC",
    "BtsI": "GCAGTG|CACTGC",
    "BtsIMutI": "CAGTG|CACTG",
    "Cac8I": "GC[ACGT][ACGT]GC",
    "ClaI": "ATCGAT",
    "CspCI": "CAA[ACGT][ACGT][ACGT][ACGT][ACGT]GTGG|CCAC[ACGT][ACGT][ACGT][ACGT][ACGT]TTG",
    "CviAII": "CATG",
    "CviKI-1": "[AG]GC[CT]",
    "CviQI": "GTAC",
    "DdeI": "CT[ACGT]AG",
    "DpnI": "GATC",
    "DpnII": "GATC",
    "DraI": "TTTAAA",
    "DraIII": "CAC[ACGT][ACGT][ACGT]GTG",
    "DrdI": "GAC[ACGT][ACGT][ACGT][ACGT][ACGT][ACGT]GTC",
    "EaeI": "[CT]GGCC[AG]",
    "EagI": "CGGCCG",
    "EarI": "CTCTTC|GAAGAG",
    "EciI": "GGCGGA|TCCGCC",
    "Eco53kI": "GAGCTC",
    "EcoNI": "CCT[ACGT][ACGT][ACGT][ACGT][ACGT]AGG",
    "EcoO109I": "[AG]GG[ACGT]CC[CT]",
    "EcoP15I": "CAGCAG|CTGCTG",
    "EcoRI": "GAATTC",
    "EcoRV": "GATATC",
    "FatI": "CATG",
    "FauI": "CCCGC|GCGGG",
    "Fnu4HI": "GC[ACGT]GC",
    "FokI": "GGATG|CATCC",
    "FseI": "GGCCGGCC",
    "FspEI": "CC|GG",
    "FspI": "TGCGCA",
    "HaeII": "[AG]GCGC[CT]",
    "HaeIII": "GGCC",
    "HgaI": "GACGC|GCGTC",
    "HhaI": "GCGC",
    "HincII": "GT[CT][AG]AC",
    "HindIII": "AAGCTT",
    "HinfI": "GA[ACGT]TC",
    "HinP1I": "GCGC",
    "HpaI": "GTTAAC",
    "HpaII": "CCGG",
    "HphI": "GGTGA|TCACC",
    "Hpy166II": "GT[ACGT][ACGT]AC",
    "Hpy188I": "TC[ACGT]GA",
    "Hpy188III": "TC[ACGT][ACGT]GA",
    "Hpy99I": "CG[AT]CG",
    "HpyAV": "CCTTC|GAAGG",
    "HpyCH4III": "AC[ACGT]GT",
    "HpyCH4IV": "ACGT",
    "HpyCH4V": "TGCA",
    "KasI": "GGCGCC",
    "KpnI": "GGTACC",
    "LpnPI": "CC[AGT]G|C[ACGT]GG",
    "MboI": "GATC",
    "MboII": "GAAGA|TCTTC",
    "MfeI": "CAATTG",
    "MluCI": "AATT",
    "MluI": "ACGCGT",
    "MlyI": "GAGTC|GACTC",
    "MmeI": "TCC[AG]AC|GT[CT]GGA",
    "MnlI": "CCTC|GAGG",
    "MscI": "TGGCCA",
    "MseI": "TTAA",
    "MslI": "CA[CT][ACGT][ACGT][ACGT][ACGT][AG]TG",
    "MspA1I": "C[AC]GC[GT]G",
    "MspI": "CCGG",
    "MspJI": "C[ACGT][ACGT][AG]|[CT][ACGT][ACGT]G",
    "MwoI": "GC[ACGT][ACGT][ACGT][ACGT][ACGT][ACGT][ACGT]GC",
    "NaeI": "GCCGGC",
    "NarI": "GGCGCC",
    "NciI": "CC[CG]GG",
    "NcoI": "CCATGG",
    "NdeI": "CATATG",
    "NgoMIV": "GCCGGC",
    "NheI": "GCTAGC",
    "NlaIII": "CATG",
    "NlaIV": "GG[ACGT][ACGT]CC",
    "NmeAIII": "GCCGAG|CTCGGC",
    "NotI": "GCGGCCGC",
    "NruI": "TCGCGA",
    "NsiI": "ATGCAT",
    "NspI": "[AG]CATG[CT]",
    "PacI": "TTAATTAA",
    "PaeR7I": "CTCGAG",
    "PciI": "ACATGT",
    "PflFI": "GAC[ACGT][ACGT][ACGT]GTC",
    "PflMI": "CCA[ACGT][ACGT][ACGT][ACGT][ACGT]TGG",
    "PhoI": "GGCC",
    "PleI": "GAGTC|GACTC",
    "PmeI": "GTTTAAAC",
    "PmlI": "CACGTG",
    "PpuMI": "[AG]GG[AT]CC[CT]",
    "PshAI": "GAC[ACGT][ACGT][ACGT][ACGT]GTC",
    "PsiI": "TTATAA",
    "PspGI": "CC[AT]GG",
    "PspOMI": "GGGCCC",
    "PspXI": "[ACG]CTCGAG[CGT]",
    "PstI": "CTGCAG",
    "PvuI": "CGATCG",
    "PvuII": "CAGCTG",
    "RsaI": "GTAC",
    "RsrII": "CGG[AT]CCG",
    "SacI": "GAGCTC",
    "SacII": "CCGCGG",
    "SalI": "GTCGAC",
    "SapI": "GCTCTTC|GAAGAGC",
    "Sau3AI": "GATC",
    "Sau96I": "GG[ACGT]CC",
    "SbfI": "CCTGCAGG",
    "ScaI": "AGTACT",
    "ScrFI": "CC[ACGT]GG",
    "SexAI": "ACC[AT]GGT",
    "SfaNI": "GCATC|GATGC",
    "SfcI": "CT[AG][CT]AG",
    "SfiI": "GGCC[ACGT][ACGT][ACGT][ACGT][ACGT]GGCC",
    "SfoI": "GGCGCC",
    "SgrAI": "C[AG]CCGG[CT]G",
    "SmaI": "CCCGGG",
    "SmlI": "CT[CT][AG]AG",
    "SnaBI": "TACGTA",
    "SpeI": "ACTAGT",
    "SphI": "GCATGC",
    "SspI": "AATATT",
    "StuI": "AGGCCT",
    "StyD4I": "CC[ACGT]GG",
    "StyI": "CC[AT][AT]GG",
    "SwaI": "ATTTAAAT",
    "TaqalphaI": "TCGA",
    "TfiI": "GA[AT]TC",
    "TliI": "CTCGAG",
    "TseI": "GC[AT]GC",
    "Tsp45I": "GT[CG]AC",
    "Tsp509I": "AATT",
    "TspMI": "CCCGGG",
    "TspRI": "CA[CG]TG",
    "Tth111I": "GAC[ACGT][ACGT][ACGT]GTC",
    "XbaI": "TCTAGA",
    "XcmI": "CCA[ACGT][ACGT][ACGT][ACGT][ACGT][ACGT][ACGT][ACGT][ACGT]TGG",
    "XhoI": "CTCGAG",
    "XmaI": "CCCGGG",
    "XmnI": "GAA[ACGT][ACGT][ACGT][ACGT]TTC",
    "ZraI": "GACGTC"
}

re_dict = {}

for site in NEB_RE_sites:
    
    re_dict[site] = {}
    
    re_dict[site]["compiled"] = re.compile(NEB_RE_sites[site])
    
    short_string = NEB_RE_sites[site]

    short_string = short_string.replace('[CGT]', 'B')
    short_string = short_string.replace('[AGT]', 'D')
    short_string = short_string.replace('[ACT]', 'H')
    short_string = short_string.replace('[GT]', 'K')
    short_string = short_string.replace('[AC]', 'M')
    short_string = short_string.replace('[ACGT]', 'N')
    short_string = short_string.replace('[AG]', 'R')
    short_string = short_string.replace('[CG]', 'S')
    short_string = short_string.replace('[ACG]', 'V')
    short_string = short_string.replace('[AT]', 'W')
    short_string = short_string.replace('[CT]', 'Y')
    
    re_dict[site]["short"] = short_string

with open("re_dict_dump", "wb") as re_dump_file:
    pickle.dump(re_dict, re_dump_file)